#include <tui.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include <stdlib.h>
static void out(const char*s,int n){write(1,s,n);}
static void outs(const char*s){write(1,s,strlen(s));}
static int fmt_int(char*buf,int n){int p=0;if(n<0){buf[p++]='-';n=-n;}char tmp[12],*t=tmp;do{*t++='0'+(n%10);n/=10;}while(n);while(t>tmp)buf[p++]=*--t;return p;}
static void ansi_goto(int y,int x){char buf[24];int p=0;buf[p++]=0x1B;buf[p++]='[';p+=fmt_int(buf+p,y+1);buf[p++]=';';p+=fmt_int(buf+p,x+1);buf[p++]='H';out(buf,p);}
typedef struct{char ch;unsigned char attr;}cell_t;
static unsigned char mk_attr(int fg,int bg){return (unsigned char)((bg<<4)|fg);}
struct tui_win_s{int x,y,w,h,flags,cx,cy,scroll_off,scroll_ok,fg,bg,bold;cell_t*buf;int*dirty;char*title;};
struct tui_s{int w,h;tui_win_t**windows;int nwindows,cap;cell_t*composite;int*comp_dirty;cell_t*phys;};
tui_t *tui_init(void){
    tui_t*t=malloc(sizeof(tui_t));if(!t)return 0;
    t->w=80;t->h=25;t->windows=0;t->nwindows=0;t->cap=0;
    t->composite=malloc(80*25*sizeof(cell_t));t->phys=malloc(80*25*sizeof(cell_t));t->comp_dirty=malloc(25*sizeof(int));
    if(!t->composite||!t->phys||!t->comp_dirty){free(t->composite);free(t->phys);free(t->comp_dirty);free(t);return 0;}
    cell_t blank={' ',mk_attr(15,0)};for(int i=0;i<80*25;i++)t->composite[i]=blank;for(int i=0;i<80*25;i++)t->phys[i]=blank;for(int i=0;i<25;i++)t->comp_dirty[i]=1;
    outs("\x1b[?25l\x1b[2J");t->phys[0].ch=0;return t;
}
void tui_end(tui_t*t){if(!t)return;for(int i=0;i<t->nwindows;i++){free(t->windows[i]->buf);free(t->windows[i]->dirty);free(t->windows[i]->title);free(t->windows[i]);}free(t->windows);free(t->composite);free(t->phys);free(t->comp_dirty);outs("\x1b[2J\x1b[H\x1b[?25h");free(t);}
tui_win_t *tui_win_new(tui_t*t,int x,int y,int w,int h,int flags){if(!t||w<1||h<1)return 0;tui_win_t*win=malloc(sizeof(tui_win_t));if(!win)return 0;win->x=x;win->y=y;win->w=w;win->h=h;win->flags=flags;win->cx=0;win->cy=0;win->scroll_off=0;win->scroll_ok=(flags&4)?1:0;win->fg=15;win->bg=0;win->bold=0;win->buf=malloc(w*h*sizeof(cell_t));win->dirty=malloc(h*sizeof(int));win->title=0;if(!win->buf||!win->dirty){free(win->buf);free(win->dirty);free(win);return 0;}cell_t blank={' ',mk_attr(win->fg,win->bg)};for(int i=0;i<w*h;i++)win->buf[i]=blank;for(int i=0;i<h;i++)win->dirty[i]=1;if(t->nwindows>=t->cap){int nc=t->cap?t->cap*2:8;tui_win_t**nw=realloc(t->windows,nc*sizeof(tui_win_t*));if(!nw){free(win->buf);free(win->dirty);free(win);return 0;}t->windows=nw;t->cap=nc;}t->windows[t->nwindows++]=win;return win;}
void tui_win_close(tui_t*t,tui_win_t*w){if(!t||!w)return;for(int i=0;i<t->nwindows;i++){if(t->windows[i]==w){free(w->buf);free(w->dirty);free(w->title);free(w);t->windows[i]=t->windows[--t->nwindows];for(int r=w->y;r<w->y+w->h&&r<t->h;r++)if(r>=0)t->comp_dirty[r]=1;return;}}}
void tui_win_move(tui_win_t*w,int x,int y){if(!w)return;w->x=x;w->y=y;for(int i=0;i<w->h;i++)w->dirty[i]=1;}
void tui_win_resize(tui_win_t*w,int nw,int nh){if(!w||nw<1||nh<1)return;cell_t*nb=malloc(nw*nh*sizeof(cell_t));int*nd=malloc(nh*sizeof(int));if(!nb||!nd){free(nb);free(nd);return;}cell_t blank={' ',mk_attr(w->fg,w->bg)};for(int i=0;i<nw*nh;i++)nb[i]=blank;for(int i=0;i<nh;i++)nd[i]=1;free(w->buf);free(w->dirty);w->buf=nb;w->dirty=nd;w->w=nw;w->h=nh;w->cx=0;w->cy=0;w->scroll_off=0;}
void tui_win_gotoxy(tui_win_t*w,int y,int x){if(!w)return;if(x<0)x=0;if(x>=w->w)x=w->w-1;if(y<0)y=0;if(y>=w->h)y=w->h-1;w->cx=x;w->cy=y;}
void tui_win_addch(tui_win_t*w,char ch){if(!w||w->cx>=w->w||w->cy>=w->h)return;int idx=w->cy*w->w+w->cx;w->buf[idx].ch=ch;w->buf[idx].attr=mk_attr(w->fg,w->bg);w->dirty[w->cy]=1;w->cx++;}
void tui_win_addch_attr(tui_win_t*w,char ch,int fg,int bg){if(!w||w->cx>=w->w||w->cy>=w->h)return;int idx=w->cy*w->w+w->cx;w->buf[idx].ch=ch;w->buf[idx].attr=mk_attr(fg,bg);w->dirty[w->cy]=1;w->cx++;}
void tui_win_addstr(tui_win_t*w,const char*s){if(!w||!s)return;while(*s){if(*s=='\n'){w->cx=0;w->cy++;if(w->cy>=w->h&&w->scroll_ok){/*scroll later*/w->cy=w->h-1;}s++;continue;}if(w->cx>=w->w){w->cx=0;w->cy++;}if(w->cy>=w->h){if(w->scroll_ok){/*scroll*/w->cy=w->h-1;}else break;}tui_win_addch(w,*s++);}}
void tui_win_color(tui_win_t*w,int fg,int bg){if(!w)return;w->fg=fg&15;w->bg=bg&15;}
void tui_win_clear(tui_win_t*w){if(!w)return;cell_t blank={' ',mk_attr(w->fg,w->bg)};for(int i=0;i<w->w*w->h;i++)w->buf[i]=blank;for(int i=0;i<w->h;i++)w->dirty[i]=1;w->cx=0;w->cy=0;w->scroll_off=0;}
void tui_win_box(tui_win_t*w,const char*title){if(!w||w->w<3||w->h<3)return;cell_t blank={' ',mk_attr(w->fg,w->bg)};w->buf[0*w->w+0].ch='+';for(int x=1;x<w->w-1;x++)w->buf[0*w->w+x].ch='-';w->buf[0*w->w+w->w-1].ch='+';w->buf[(w->h-1)*w->w+0].ch='+';for(int x=1;x<w->w-1;x++)w->buf[(w->h-1)*w->w+x].ch='-';w->buf[(w->h-1)*w->w+w->w-1].ch='+';for(int y=1;y<w->h-1;y++){w->buf[y*w->w+0].ch='|';w->buf[y*w->w+w->w-1].ch='|';}for(int y=1;y<w->h-1;y++)for(int x=1;x<w->w-1;x++)w->buf[y*w->w+x]=blank;if(title&&*title){int sl=strlen(title);int max=w->w-3;if(sl>max)sl=max;for(int i=0;i<sl;i++)w->buf[0*w->w+2+i].ch=title[i];}for(int i=0;i<w->h;i++)w->dirty[i]=1;}
static void composite(tui_t*t){cell_t blank={' ',mk_attr(15,0)};for(int i=0;i<t->w*t->h;i++)t->composite[i]=blank;for(int wi=0;wi<t->nwindows;wi++){tui_win_t*w=t->windows[wi];for(int row=0;row<w->h;row++){int sy=w->y+row;if(sy<0||sy>=t->h)continue;for(int col=0;col<w->w;col++){int sx=w->x+col;if(sx<0||sx>=t->w)continue;t->composite[sy*t->w+sx]=w->buf[row*w->w+col];}}}}
void tui_refresh(tui_t*t){if(!t)return;composite(t);for(int row=0;row<t->h;row++){cell_t*cr=&t->composite[row*t->w];cell_t*pr=&t->phys[row*t->w];int ch=0;for(int c=0;c<t->w;c++){if(cr[c].ch!=pr[c].ch||cr[c].attr!=pr[c].attr){ch=1;break;}}if(!ch)continue;ansi_goto(row,0);int cur_fg=-1,cur_bg=-1;int last=-1;for(int c=t->w-1;c>=0;c--)if(cr[c].ch!=' '){last=c;break;}if(last<0){outs("\x1b[K");memcpy(pr,cr,t->w*sizeof(cell_t));continue;}for(int c=0;c<=last;c++){int fg=cr[c].attr&0x0F;int bg=(cr[c].attr>>4)&0x0F;if(fg!=cur_fg||bg!=cur_bg){cur_fg=fg;cur_bg=bg;char buf[32];int p=0;buf[p++]=0x1B;buf[p++]='[';int ansi_fg=(fg&8)?90+(fg&7):30+fg;int ansi_bg=(bg&8)?100+(bg&7):40+bg;p+=fmt_int(buf+p,ansi_fg);buf[p++]=';';p+=fmt_int(buf+p,ansi_bg);buf[p++]='m';out(buf,p);}char cc=cr[c].ch;if(cc<0x20&&cc!='\t')cc=' ';write(1,&cc,1);}if(last<t->w-1)outs("\x1b[K");memcpy(pr,cr,t->w*sizeof(cell_t));}}
static int tui_parse_escape(tui_t*t){(void)t;char c=getchar();if(c!='['&&c!='O')return 27;char seq[8];int n=0;seq[n++]=0x1B;seq[n++]=c;while(n<7){if(kbhit()){seq[n++]=getchar();if(seq[n-1]>=0x40&&seq[n-1]<=0x7e)break;if(seq[n-1]=='~')break;}else return 27;}if(n==3&&seq[1]=='['){if(seq[2]>='A'&&seq[2]<='D')return 300+(seq[2]-'A');if(seq[2]=='H')return 304;if(seq[2]=='F')return 305;}if(n==3&&seq[1]=='O'){if(seq[2]>='A'&&seq[2]<='D')return 300+(seq[2]-'A');if(seq[2]=='H')return 304;if(seq[2]=='F')return 305;if(seq[2]>='P'&&seq[2]<='S')return 310+(seq[2]-'P');}if(n>=4&&seq[1]=='['){if(seq[2]=='2'&&seq[3]=='~')return 308;if(seq[2]=='3'&&seq[3]=='~')return 309;if(seq[2]=='5'&&seq[3]=='~')return 306;if(seq[2]=='6'&&seq[3]=='~')return 307;if(n>=5){if(seq[2]=='1'&&seq[3]=='5'&&seq[4]=='~')return 314;if(seq[2]=='1'&&seq[3]=='7'&&seq[4]=='~')return 315;if(seq[2]=='1'&&seq[3]=='8'&&seq[4]=='~')return 316;if(seq[2]=='1'&&seq[3]=='9'&&seq[4]=='~')return 317;if(seq[2]=='2'&&seq[3]=='0'&&seq[4]=='~')return 318;}}return 27;}
int tui_getch(tui_t*t){(void)t;char c=getchar();if(c!=0x1B)return(unsigned char)c;return tui_parse_escape(t);}
int tui_poll_event(tui_t*t,tui_event_t*ev){if(!t||!ev)return 0;if(!kbhit())return 0;ev->type=1;ev->key=tui_getch(t);return 1;}
int tui_dialog(tui_t*t,const char*title,const char*msg,const char*btns){if(!t||!msg)return -1;int bw=t->w*2/3;if(bw<30)bw=30;if(bw>t->w)bw=t->w;int bh=7;int bx=(t->w-bw)/2;int by=(t->h-bh)/2;tui_win_t*w=tui_win_new(t,bx,by,bw,bh,0);if(!w)return -1;tui_win_box(w,title?title:"");tui_win_color(w,15,0);int my=1;const char*p=msg;while(*p){int col=0;while(*p&&*p!='\n'&&col<bw-2){tui_win_gotoxy(w,my,2+col);tui_win_addch(w,*p++);col++;}if(*p=='\n')p++;my++;if(my>=bh-1)break;}if(btns&&*btns){int bn=0;while(btns[bn])bn++;int blen=bn+2;int bs=(bw-blen)/2;if(bs<0)bs=0;tui_win_gotoxy(w,bh-1,bs);tui_win_addch(w,'[');tui_win_addstr(w,btns);tui_win_addch(w,']');}tui_refresh(t);int k=tui_getch(t);int bk=-1;if(k==10&&btns)bk=0;else if(k==27)bk=-1;tui_win_close(t,w);tui_refresh(t);return bk;}
void tui_msgbox(tui_t*t,const char*title,const char*msg){tui_dialog(t,title,msg,"OK");}
